sudo: false
language: python

python:
  - 2.7
  - 3.3

env:
  - DEPS="numpy=1.8 matplotlib=1.3 jinja2=2.7.2 pandas=0.13.1 nose"

install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes $DEPS
  - python setup.py install

before_install:
  # install npm packages first, to use system python
  - npm config set python python2.7
  - npm install d3 vows smash jsdom
  # then install python version to test
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Learned the hard way: miniconda is not always up-to-date with conda.
  - conda update --yes conda
  # start Virtual X, so default matplotlib backend works
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - nosetests mpld3
  - make test  # Javascript tests
